### ISSUE TITLE
Seed, process, 512 tile size

### ISSUE THREAD

**Issue by gswierczynski** [tilezen/tilequeue#277]
Hi,

Using seed and process commands I managed to generate tiles. They have 256 size.

Is it possible to produce tiles with 512 size that way?

I failed to find config for that. Is it something that is done in post processing?

Thanks,
Greg.

**Comment by gswierczynski** [comment]
I digged a little more and I understand that the "metatile" settings is responsible for generating groups of tiles packed in zip archives and it is responsibility of the tile server to create final tile.
I found mentions of Tapalcatl, but I suppose tileserver does that as well.
Is that correct?

**Comment by zerebubuth** [comment]
Yes, you're quite right; [the `metatile` config setting](https://github.com/tilezen/tilequeue/blob/7ec2722014592606cffc4ce165c17f4bb048bb14/config.yaml.sample#L198) controls whether 512px tiles are written out.

Thanks for pointing it out, because the comment is wrong! We now support a size of 2, which means 512px tiles, in addition to 1 and `null`. I will update the comment.

[Tileserver](https://github.com/tilezen/tileserver/) can handle generating either 256px or 512px tiles, but doesn't store them in `.zip` files or read them from the store. Reading them from the store is the function of [tapalcatl](https://github.com/tilezen/tapalcatl/) and storing them is done by [tilequeue](https://github.com/tilezen/tilequeue/).

We do this because we pass requests through a series of layers; the first is the edge cache CDN, the second is tapalcatl, and the third is tileserver. By the time a request reaches tileserver, we know that tapalcatl failed to serve it from the store, so there is no need to check it again in tileserver.

**Comment by nvkelso** [comment]
@gswierczynski Please let us know if you need any further assistance.

**Comment by gswierczynski** [comment]
Thank you for taking time to clarify this. It helped me a lot.

I wrapped my head around tapalcatl and managed to serve 512 tiles generated by tilequeue.

I understand why the metatile holds both 512 and 256, but is there a simple way to prevent tilequeue from writing 256 ones to the archive (that would significantly reduce the footprint on disk in scenarios where 256 tile size support is not required).

Is https://github.com/tilezen/tilequeue/blob/master/tilequeue/metatile.py a good place to start?
